// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Rule = 2,
  UnaryExpression = 3,
  Not = 4,
  Deontics = 5,
  RuleIndicator = 6,
  LoopExpression = 7,
  Loop = 8,
  TernaryExpression = 9,
  Logic = 10,
  BinaryExpression = 11,
  Function = 12,
  Atom = 13,
  Variable = 14,
  Property = 15,
  Data = 16,
  DataTernaryExpression = 17
